services:
    api:
        build: .
        ports:
            - 8000:8000
        volumes:
            - ./app:/app/app:ro
        env_file:
            -  .env
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        # depends_on:
        #     - postgres
        
#     postgres:
#         image: postgres
#         environment:
#             - POSTGRES_PASSWORD=$(DATABASE_PASSWORD)
#             - POSTGRES_DB=$(DATABASE_NAME)

#         volumes:
#             - postgres-db:/var/lib/postgresql/data

# volumes:
#     postgres-db: